"""initial schema

Revision ID: d22c552b250b
Revises: 
Create Date: 2026-07-18 03:59:55.425373
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd22c552b250b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_memory',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_ai_memory_key')
    )
    op.create_index(op.f('ix_ai_memory_key'), 'ai_memory', ['key'], unique=False)
    op.create_table('categories',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_warmth', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('colors',
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('hex', sa.String(length=7), nullable=False),
    sa.Column('family', sa.String(length=24), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colors_family'), 'colors', ['family'], unique=False)
    op.create_index(op.f('ix_colors_name'), 'colors', ['name'], unique=True)
    op.create_table('favorites',
    sa.Column('target_type', sa.Enum('item', 'outfit', name='favorite_target_enum', native_enum=False, length=32), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', name='uq_favorite_target')
    )
    op.create_index(op.f('ix_favorites_target_id'), 'favorites', ['target_id'], unique=False)
    op.create_table('outfits',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occasion', sa.Enum('everyday', 'work', 'workout', 'date', 'party', 'formal_event', 'travel', 'outdoor', name='occasion_enum', native_enum=False, length=32), nullable=False),
    sa.Column('formality', sa.Enum('lounge', 'casual', 'smart_casual', 'business', 'formal', name='formality_enum', native_enum=False, length=32), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('wear_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('weather_cache',
    sa.Column('latitude', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('for_date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('condition', sa.Enum('clear', 'cloudy', 'rain', 'snow', 'storm', 'fog', name='weather_condition_enum', native_enum=False, length=32), nullable=False),
    sa.Column('temp_min_c', sa.Float(), nullable=False),
    sa.Column('temp_max_c', sa.Float(), nullable=False),
    sa.Column('temp_current_c', sa.Float(), nullable=True),
    sa.Column('precipitation_prob', sa.Float(), nullable=True),
    sa.Column('wind_kph', sa.Float(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('latitude', 'longitude', 'for_date', name='uq_weather_loc_date')
    )
    op.create_table('clothing_items',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('size', sa.String(length=32), nullable=True),
    sa.Column('material', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('season', sa.Enum('spring', 'summer', 'autumn', 'winter', 'all_season', name='season_enum', native_enum=False, length=32), nullable=False),
    sa.Column('formality', sa.Enum('lounge', 'casual', 'smart_casual', 'business', 'formal', name='formality_enum', native_enum=False, length=32), nullable=False),
    sa.Column('warmth', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('wear_count', sa.Integer(), nullable=False),
    sa.Column('last_worn_at', sa.Date(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clothing_items_category_id'), 'clothing_items', ['category_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('occasion', sa.Enum('everyday', 'work', 'workout', 'date', 'party', 'formal_event', 'travel', 'outdoor', name='occasion_enum', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('suggested', 'accepted', 'dismissed', 'worn', name='recommendation_status_enum', native_enum=False, length=32), nullable=False),
    sa.Column('used_ai', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weather_id', sa.BigInteger(), nullable=True),
    sa.Column('outfit_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['weather_id'], ['weather_cache.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_table('item_colors',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('color_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['clothing_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'color_id')
    )
    op.create_table('item_tags',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['clothing_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    op.create_table('outfit_items',
    sa.Column('outfit_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['clothing_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outfit_id', 'item_id', name='uq_outfit_item')
    )
    op.create_index(op.f('ix_outfit_items_item_id'), 'outfit_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_outfit_items_outfit_id'), 'outfit_items', ['outfit_id'], unique=False)
    op.create_table('wear_log',
    sa.Column('worn_on', sa.Date(), nullable=False),
    sa.Column('outfit_id', sa.BigInteger(), nullable=True),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['clothing_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wear_log_item_id'), 'wear_log', ['item_id'], unique=False)
    op.create_index(op.f('ix_wear_log_outfit_id'), 'wear_log', ['outfit_id'], unique=False)
    op.create_index(op.f('ix_wear_log_worn_on'), 'wear_log', ['worn_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wear_log_worn_on'), table_name='wear_log')
    op.drop_index(op.f('ix_wear_log_outfit_id'), table_name='wear_log')
    op.drop_index(op.f('ix_wear_log_item_id'), table_name='wear_log')
    op.drop_table('wear_log')
    op.drop_index(op.f('ix_outfit_items_outfit_id'), table_name='outfit_items')
    op.drop_index(op.f('ix_outfit_items_item_id'), table_name='outfit_items')
    op.drop_table('outfit_items')
    op.drop_table('item_tags')
    op.drop_table('item_colors')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_clothing_items_category_id'), table_name='clothing_items')
    op.drop_table('clothing_items')
    op.drop_table('weather_cache')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('outfits')
    op.drop_index(op.f('ix_favorites_target_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_colors_name'), table_name='colors')
    op.drop_index(op.f('ix_colors_family'), table_name='colors')
    op.drop_table('colors')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_ai_memory_key'), table_name='ai_memory')
    op.drop_table('ai_memory')
    # ### end Alembic commands ###
